// Code generated by protoc-gen-go. DO NOT EDIT.
// source: consul.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConsulEmpty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsulEmpty) Reset()         { *m = ConsulEmpty{} }
func (m *ConsulEmpty) String() string { return proto.CompactTextString(m) }
func (*ConsulEmpty) ProtoMessage()    {}
func (*ConsulEmpty) Descriptor() ([]byte, []int) {
	return fileDescriptor_665b1cce082a77c9, []int{0}
}

func (m *ConsulEmpty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsulEmpty.Unmarshal(m, b)
}
func (m *ConsulEmpty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsulEmpty.Marshal(b, m, deterministic)
}
func (m *ConsulEmpty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsulEmpty.Merge(m, src)
}
func (m *ConsulEmpty) XXX_Size() int {
	return xxx_messageInfo_ConsulEmpty.Size(m)
}
func (m *ConsulEmpty) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsulEmpty.DiscardUnknown(m)
}

var xxx_messageInfo_ConsulEmpty proto.InternalMessageInfo

type AgentWeights struct {
	Passing              int32    `protobuf:"varint,1,opt,name=passing,proto3" json:"passing,omitempty"`
	Warning              int32    `protobuf:"varint,2,opt,name=warning,proto3" json:"warning,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentWeights) Reset()         { *m = AgentWeights{} }
func (m *AgentWeights) String() string { return proto.CompactTextString(m) }
func (*AgentWeights) ProtoMessage()    {}
func (*AgentWeights) Descriptor() ([]byte, []int) {
	return fileDescriptor_665b1cce082a77c9, []int{1}
}

func (m *AgentWeights) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentWeights.Unmarshal(m, b)
}
func (m *AgentWeights) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentWeights.Marshal(b, m, deterministic)
}
func (m *AgentWeights) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentWeights.Merge(m, src)
}
func (m *AgentWeights) XXX_Size() int {
	return xxx_messageInfo_AgentWeights.Size(m)
}
func (m *AgentWeights) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentWeights.DiscardUnknown(m)
}

var xxx_messageInfo_AgentWeights proto.InternalMessageInfo

func (m *AgentWeights) GetPassing() int32 {
	if m != nil {
		return m.Passing
	}
	return 0
}

func (m *AgentWeights) GetWarning() int32 {
	if m != nil {
		return m.Warning
	}
	return 0
}

type ServiceAddress struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceAddress) Reset()         { *m = ServiceAddress{} }
func (m *ServiceAddress) String() string { return proto.CompactTextString(m) }
func (*ServiceAddress) ProtoMessage()    {}
func (*ServiceAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_665b1cce082a77c9, []int{2}
}

func (m *ServiceAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceAddress.Unmarshal(m, b)
}
func (m *ServiceAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceAddress.Marshal(b, m, deterministic)
}
func (m *ServiceAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceAddress.Merge(m, src)
}
func (m *ServiceAddress) XXX_Size() int {
	return xxx_messageInfo_ServiceAddress.Size(m)
}
func (m *ServiceAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceAddress.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceAddress proto.InternalMessageInfo

func (m *ServiceAddress) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ServiceAddress) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type GetServiceArgs struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tags                 string   `protobuf:"bytes,2,opt,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetServiceArgs) Reset()         { *m = GetServiceArgs{} }
func (m *GetServiceArgs) String() string { return proto.CompactTextString(m) }
func (*GetServiceArgs) ProtoMessage()    {}
func (*GetServiceArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_665b1cce082a77c9, []int{3}
}

func (m *GetServiceArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServiceArgs.Unmarshal(m, b)
}
func (m *GetServiceArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServiceArgs.Marshal(b, m, deterministic)
}
func (m *GetServiceArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServiceArgs.Merge(m, src)
}
func (m *GetServiceArgs) XXX_Size() int {
	return xxx_messageInfo_GetServiceArgs.Size(m)
}
func (m *GetServiceArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServiceArgs.DiscardUnknown(m)
}

var xxx_messageInfo_GetServiceArgs proto.InternalMessageInfo

func (m *GetServiceArgs) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetServiceArgs) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

type GetServiceReply struct {
	Kind                 string                     `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Id                   string                     `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Service              string                     `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Tags                 []string                   `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Meta                 map[string]string          `protobuf:"bytes,5,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Port                 int32                      `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	Address              string                     `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	TaggedAddresses      map[string]*ServiceAddress `protobuf:"bytes,8,rep,name=taggedAddresses,proto3" json:"taggedAddresses,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Weights              *AgentWeights              `protobuf:"bytes,9,opt,name=Weights,proto3" json:"Weights,omitempty"`
	EnableTagOverride    bool                       `protobuf:"varint,10,opt,name=enableTagOverride,proto3" json:"enableTagOverride,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GetServiceReply) Reset()         { *m = GetServiceReply{} }
func (m *GetServiceReply) String() string { return proto.CompactTextString(m) }
func (*GetServiceReply) ProtoMessage()    {}
func (*GetServiceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_665b1cce082a77c9, []int{4}
}

func (m *GetServiceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServiceReply.Unmarshal(m, b)
}
func (m *GetServiceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServiceReply.Marshal(b, m, deterministic)
}
func (m *GetServiceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServiceReply.Merge(m, src)
}
func (m *GetServiceReply) XXX_Size() int {
	return xxx_messageInfo_GetServiceReply.Size(m)
}
func (m *GetServiceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServiceReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetServiceReply proto.InternalMessageInfo

func (m *GetServiceReply) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *GetServiceReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetServiceReply) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *GetServiceReply) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *GetServiceReply) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *GetServiceReply) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *GetServiceReply) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GetServiceReply) GetTaggedAddresses() map[string]*ServiceAddress {
	if m != nil {
		return m.TaggedAddresses
	}
	return nil
}

func (m *GetServiceReply) GetWeights() *AgentWeights {
	if m != nil {
		return m.Weights
	}
	return nil
}

func (m *GetServiceReply) GetEnableTagOverride() bool {
	if m != nil {
		return m.EnableTagOverride
	}
	return false
}

type NewSessionArgs struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ttl                  string   `protobuf:"bytes,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Behavior             string   `protobuf:"bytes,3,opt,name=behavior,proto3" json:"behavior,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewSessionArgs) Reset()         { *m = NewSessionArgs{} }
func (m *NewSessionArgs) String() string { return proto.CompactTextString(m) }
func (*NewSessionArgs) ProtoMessage()    {}
func (*NewSessionArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_665b1cce082a77c9, []int{5}
}

func (m *NewSessionArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewSessionArgs.Unmarshal(m, b)
}
func (m *NewSessionArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewSessionArgs.Marshal(b, m, deterministic)
}
func (m *NewSessionArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewSessionArgs.Merge(m, src)
}
func (m *NewSessionArgs) XXX_Size() int {
	return xxx_messageInfo_NewSessionArgs.Size(m)
}
func (m *NewSessionArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_NewSessionArgs.DiscardUnknown(m)
}

var xxx_messageInfo_NewSessionArgs proto.InternalMessageInfo

func (m *NewSessionArgs) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewSessionArgs) GetTtl() string {
	if m != nil {
		return m.Ttl
	}
	return ""
}

func (m *NewSessionArgs) GetBehavior() string {
	if m != nil {
		return m.Behavior
	}
	return ""
}

type ServiceCheck struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceCheck) Reset()         { *m = ServiceCheck{} }
func (m *ServiceCheck) String() string { return proto.CompactTextString(m) }
func (*ServiceCheck) ProtoMessage()    {}
func (*ServiceCheck) Descriptor() ([]byte, []int) {
	return fileDescriptor_665b1cce082a77c9, []int{6}
}

func (m *ServiceCheck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceCheck.Unmarshal(m, b)
}
func (m *ServiceCheck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceCheck.Marshal(b, m, deterministic)
}
func (m *ServiceCheck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceCheck.Merge(m, src)
}
func (m *ServiceCheck) XXX_Size() int {
	return xxx_messageInfo_ServiceCheck.Size(m)
}
func (m *ServiceCheck) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceCheck.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceCheck proto.InternalMessageInfo

func (m *ServiceCheck) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ServiceCheck) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type SessionEntry struct {
	CreateIndex          uint64          `protobuf:"varint,1,opt,name=CreateIndex,proto3" json:"CreateIndex,omitempty"`
	ID                   string          `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string          `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Node                 string          `protobuf:"bytes,4,opt,name=Node,proto3" json:"Node,omitempty"`
	LockDelay            string          `protobuf:"bytes,5,opt,name=LockDelay,proto3" json:"LockDelay,omitempty"`
	Behavior             string          `protobuf:"bytes,6,opt,name=Behavior,proto3" json:"Behavior,omitempty"`
	TTL                  string          `protobuf:"bytes,7,opt,name=TTL,proto3" json:"TTL,omitempty"`
	Checks               []string        `protobuf:"bytes,8,rep,name=Checks,proto3" json:"Checks,omitempty"`
	NodeChecks           []string        `protobuf:"bytes,9,rep,name=NodeChecks,proto3" json:"NodeChecks,omitempty"`
	ServiceChecks        []*ServiceCheck `protobuf:"bytes,10,rep,name=ServiceChecks,proto3" json:"ServiceChecks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SessionEntry) Reset()         { *m = SessionEntry{} }
func (m *SessionEntry) String() string { return proto.CompactTextString(m) }
func (*SessionEntry) ProtoMessage()    {}
func (*SessionEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_665b1cce082a77c9, []int{7}
}

func (m *SessionEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionEntry.Unmarshal(m, b)
}
func (m *SessionEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionEntry.Marshal(b, m, deterministic)
}
func (m *SessionEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionEntry.Merge(m, src)
}
func (m *SessionEntry) XXX_Size() int {
	return xxx_messageInfo_SessionEntry.Size(m)
}
func (m *SessionEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionEntry.DiscardUnknown(m)
}

var xxx_messageInfo_SessionEntry proto.InternalMessageInfo

func (m *SessionEntry) GetCreateIndex() uint64 {
	if m != nil {
		return m.CreateIndex
	}
	return 0
}

func (m *SessionEntry) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *SessionEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SessionEntry) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *SessionEntry) GetLockDelay() string {
	if m != nil {
		return m.LockDelay
	}
	return ""
}

func (m *SessionEntry) GetBehavior() string {
	if m != nil {
		return m.Behavior
	}
	return ""
}

func (m *SessionEntry) GetTTL() string {
	if m != nil {
		return m.TTL
	}
	return ""
}

func (m *SessionEntry) GetChecks() []string {
	if m != nil {
		return m.Checks
	}
	return nil
}

func (m *SessionEntry) GetNodeChecks() []string {
	if m != nil {
		return m.NodeChecks
	}
	return nil
}

func (m *SessionEntry) GetServiceChecks() []*ServiceCheck {
	if m != nil {
		return m.ServiceChecks
	}
	return nil
}

type NewSessionReply struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewSessionReply) Reset()         { *m = NewSessionReply{} }
func (m *NewSessionReply) String() string { return proto.CompactTextString(m) }
func (*NewSessionReply) ProtoMessage()    {}
func (*NewSessionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_665b1cce082a77c9, []int{8}
}

func (m *NewSessionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewSessionReply.Unmarshal(m, b)
}
func (m *NewSessionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewSessionReply.Marshal(b, m, deterministic)
}
func (m *NewSessionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewSessionReply.Merge(m, src)
}
func (m *NewSessionReply) XXX_Size() int {
	return xxx_messageInfo_NewSessionReply.Size(m)
}
func (m *NewSessionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_NewSessionReply.DiscardUnknown(m)
}

var xxx_messageInfo_NewSessionReply proto.InternalMessageInfo

func (m *NewSessionReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SessionInfoArgs struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionInfoArgs) Reset()         { *m = SessionInfoArgs{} }
func (m *SessionInfoArgs) String() string { return proto.CompactTextString(m) }
func (*SessionInfoArgs) ProtoMessage()    {}
func (*SessionInfoArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_665b1cce082a77c9, []int{9}
}

func (m *SessionInfoArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionInfoArgs.Unmarshal(m, b)
}
func (m *SessionInfoArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionInfoArgs.Marshal(b, m, deterministic)
}
func (m *SessionInfoArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionInfoArgs.Merge(m, src)
}
func (m *SessionInfoArgs) XXX_Size() int {
	return xxx_messageInfo_SessionInfoArgs.Size(m)
}
func (m *SessionInfoArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionInfoArgs.DiscardUnknown(m)
}

var xxx_messageInfo_SessionInfoArgs proto.InternalMessageInfo

func (m *SessionInfoArgs) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SessionInfoReply struct {
	Entry                *SessionEntry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SessionInfoReply) Reset()         { *m = SessionInfoReply{} }
func (m *SessionInfoReply) String() string { return proto.CompactTextString(m) }
func (*SessionInfoReply) ProtoMessage()    {}
func (*SessionInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_665b1cce082a77c9, []int{10}
}

func (m *SessionInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionInfoReply.Unmarshal(m, b)
}
func (m *SessionInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionInfoReply.Marshal(b, m, deterministic)
}
func (m *SessionInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionInfoReply.Merge(m, src)
}
func (m *SessionInfoReply) XXX_Size() int {
	return xxx_messageInfo_SessionInfoReply.Size(m)
}
func (m *SessionInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_SessionInfoReply proto.InternalMessageInfo

func (m *SessionInfoReply) GetEntry() *SessionEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type DestroySessionArgs struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DestroySessionArgs) Reset()         { *m = DestroySessionArgs{} }
func (m *DestroySessionArgs) String() string { return proto.CompactTextString(m) }
func (*DestroySessionArgs) ProtoMessage()    {}
func (*DestroySessionArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_665b1cce082a77c9, []int{11}
}

func (m *DestroySessionArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestroySessionArgs.Unmarshal(m, b)
}
func (m *DestroySessionArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestroySessionArgs.Marshal(b, m, deterministic)
}
func (m *DestroySessionArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestroySessionArgs.Merge(m, src)
}
func (m *DestroySessionArgs) XXX_Size() int {
	return xxx_messageInfo_DestroySessionArgs.Size(m)
}
func (m *DestroySessionArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_DestroySessionArgs.DiscardUnknown(m)
}

var xxx_messageInfo_DestroySessionArgs proto.InternalMessageInfo

func (m *DestroySessionArgs) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type KVPair struct {
	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	// CreateIndex holds the index corresponding the creation of this KVPair. This
	// is a read-only field.
	CreateIndex uint64 `protobuf:"varint,2,opt,name=CreateIndex,proto3" json:"CreateIndex,omitempty"`
	// ModifyIndex is used for the Check-And-Set operations and can also be fed
	// back into the WaitIndex of the QueryOptions in order to perform blocking
	// queries.
	ModifyIndex uint64 `protobuf:"varint,3,opt,name=ModifyIndex,proto3" json:"ModifyIndex,omitempty"`
	// LockIndex holds the index corresponding to a lock on this key, if any. This
	// is a read-only field.
	LockIndex uint64 `protobuf:"varint,4,opt,name=LockIndex,proto3" json:"LockIndex,omitempty"`
	// Flags are any user-defined flags on the key. It is up to the implementer
	// to check these values, since Consul does not treat them specially.
	Flags uint64 `protobuf:"varint,5,opt,name=Flags,proto3" json:"Flags,omitempty"`
	// Value is the value for the key. This can be any value, but it will be
	// base64 encoded upon transport.
	Value []byte `protobuf:"bytes,6,opt,name=Value,proto3" json:"Value,omitempty"`
	// Session is a string representing the ID of the session. Any other
	// interactions with this key over the same session must specify the same
	// session ID.
	Session              string   `protobuf:"bytes,7,opt,name=Session,proto3" json:"Session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KVPair) Reset()         { *m = KVPair{} }
func (m *KVPair) String() string { return proto.CompactTextString(m) }
func (*KVPair) ProtoMessage()    {}
func (*KVPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_665b1cce082a77c9, []int{12}
}

func (m *KVPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KVPair.Unmarshal(m, b)
}
func (m *KVPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KVPair.Marshal(b, m, deterministic)
}
func (m *KVPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVPair.Merge(m, src)
}
func (m *KVPair) XXX_Size() int {
	return xxx_messageInfo_KVPair.Size(m)
}
func (m *KVPair) XXX_DiscardUnknown() {
	xxx_messageInfo_KVPair.DiscardUnknown(m)
}

var xxx_messageInfo_KVPair proto.InternalMessageInfo

func (m *KVPair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KVPair) GetCreateIndex() uint64 {
	if m != nil {
		return m.CreateIndex
	}
	return 0
}

func (m *KVPair) GetModifyIndex() uint64 {
	if m != nil {
		return m.ModifyIndex
	}
	return 0
}

func (m *KVPair) GetLockIndex() uint64 {
	if m != nil {
		return m.LockIndex
	}
	return 0
}

func (m *KVPair) GetFlags() uint64 {
	if m != nil {
		return m.Flags
	}
	return 0
}

func (m *KVPair) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *KVPair) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

type KVAcquireArgs struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Session              string   `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KVAcquireArgs) Reset()         { *m = KVAcquireArgs{} }
func (m *KVAcquireArgs) String() string { return proto.CompactTextString(m) }
func (*KVAcquireArgs) ProtoMessage()    {}
func (*KVAcquireArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_665b1cce082a77c9, []int{13}
}

func (m *KVAcquireArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KVAcquireArgs.Unmarshal(m, b)
}
func (m *KVAcquireArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KVAcquireArgs.Marshal(b, m, deterministic)
}
func (m *KVAcquireArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVAcquireArgs.Merge(m, src)
}
func (m *KVAcquireArgs) XXX_Size() int {
	return xxx_messageInfo_KVAcquireArgs.Size(m)
}
func (m *KVAcquireArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_KVAcquireArgs.DiscardUnknown(m)
}

var xxx_messageInfo_KVAcquireArgs proto.InternalMessageInfo

func (m *KVAcquireArgs) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KVAcquireArgs) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

type KVAcquireReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KVAcquireReply) Reset()         { *m = KVAcquireReply{} }
func (m *KVAcquireReply) String() string { return proto.CompactTextString(m) }
func (*KVAcquireReply) ProtoMessage()    {}
func (*KVAcquireReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_665b1cce082a77c9, []int{14}
}

func (m *KVAcquireReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KVAcquireReply.Unmarshal(m, b)
}
func (m *KVAcquireReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KVAcquireReply.Marshal(b, m, deterministic)
}
func (m *KVAcquireReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVAcquireReply.Merge(m, src)
}
func (m *KVAcquireReply) XXX_Size() int {
	return xxx_messageInfo_KVAcquireReply.Size(m)
}
func (m *KVAcquireReply) XXX_DiscardUnknown() {
	xxx_messageInfo_KVAcquireReply.DiscardUnknown(m)
}

var xxx_messageInfo_KVAcquireReply proto.InternalMessageInfo

func (m *KVAcquireReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type KVReleaseArgs struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KVReleaseArgs) Reset()         { *m = KVReleaseArgs{} }
func (m *KVReleaseArgs) String() string { return proto.CompactTextString(m) }
func (*KVReleaseArgs) ProtoMessage()    {}
func (*KVReleaseArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_665b1cce082a77c9, []int{15}
}

func (m *KVReleaseArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KVReleaseArgs.Unmarshal(m, b)
}
func (m *KVReleaseArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KVReleaseArgs.Marshal(b, m, deterministic)
}
func (m *KVReleaseArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVReleaseArgs.Merge(m, src)
}
func (m *KVReleaseArgs) XXX_Size() int {
	return xxx_messageInfo_KVReleaseArgs.Size(m)
}
func (m *KVReleaseArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_KVReleaseArgs.DiscardUnknown(m)
}

var xxx_messageInfo_KVReleaseArgs proto.InternalMessageInfo

func (m *KVReleaseArgs) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type KVInfoArgs struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KVInfoArgs) Reset()         { *m = KVInfoArgs{} }
func (m *KVInfoArgs) String() string { return proto.CompactTextString(m) }
func (*KVInfoArgs) ProtoMessage()    {}
func (*KVInfoArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_665b1cce082a77c9, []int{16}
}

func (m *KVInfoArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KVInfoArgs.Unmarshal(m, b)
}
func (m *KVInfoArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KVInfoArgs.Marshal(b, m, deterministic)
}
func (m *KVInfoArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVInfoArgs.Merge(m, src)
}
func (m *KVInfoArgs) XXX_Size() int {
	return xxx_messageInfo_KVInfoArgs.Size(m)
}
func (m *KVInfoArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_KVInfoArgs.DiscardUnknown(m)
}

var xxx_messageInfo_KVInfoArgs proto.InternalMessageInfo

func (m *KVInfoArgs) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type KVInfoReply struct {
	Kvpair               *KVPair  `protobuf:"bytes,1,opt,name=kvpair,proto3" json:"kvpair,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KVInfoReply) Reset()         { *m = KVInfoReply{} }
func (m *KVInfoReply) String() string { return proto.CompactTextString(m) }
func (*KVInfoReply) ProtoMessage()    {}
func (*KVInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_665b1cce082a77c9, []int{17}
}

func (m *KVInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KVInfoReply.Unmarshal(m, b)
}
func (m *KVInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KVInfoReply.Marshal(b, m, deterministic)
}
func (m *KVInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVInfoReply.Merge(m, src)
}
func (m *KVInfoReply) XXX_Size() int {
	return xxx_messageInfo_KVInfoReply.Size(m)
}
func (m *KVInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_KVInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_KVInfoReply proto.InternalMessageInfo

func (m *KVInfoReply) GetKvpair() *KVPair {
	if m != nil {
		return m.Kvpair
	}
	return nil
}

type KVCasArgs struct {
	Kvpair               *KVPair  `protobuf:"bytes,1,opt,name=kvpair,proto3" json:"kvpair,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KVCasArgs) Reset()         { *m = KVCasArgs{} }
func (m *KVCasArgs) String() string { return proto.CompactTextString(m) }
func (*KVCasArgs) ProtoMessage()    {}
func (*KVCasArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_665b1cce082a77c9, []int{18}
}

func (m *KVCasArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KVCasArgs.Unmarshal(m, b)
}
func (m *KVCasArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KVCasArgs.Marshal(b, m, deterministic)
}
func (m *KVCasArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVCasArgs.Merge(m, src)
}
func (m *KVCasArgs) XXX_Size() int {
	return xxx_messageInfo_KVCasArgs.Size(m)
}
func (m *KVCasArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_KVCasArgs.DiscardUnknown(m)
}

var xxx_messageInfo_KVCasArgs proto.InternalMessageInfo

func (m *KVCasArgs) GetKvpair() *KVPair {
	if m != nil {
		return m.Kvpair
	}
	return nil
}

type KVCasReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KVCasReply) Reset()         { *m = KVCasReply{} }
func (m *KVCasReply) String() string { return proto.CompactTextString(m) }
func (*KVCasReply) ProtoMessage()    {}
func (*KVCasReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_665b1cce082a77c9, []int{19}
}

func (m *KVCasReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KVCasReply.Unmarshal(m, b)
}
func (m *KVCasReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KVCasReply.Marshal(b, m, deterministic)
}
func (m *KVCasReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVCasReply.Merge(m, src)
}
func (m *KVCasReply) XXX_Size() int {
	return xxx_messageInfo_KVCasReply.Size(m)
}
func (m *KVCasReply) XXX_DiscardUnknown() {
	xxx_messageInfo_KVCasReply.DiscardUnknown(m)
}

var xxx_messageInfo_KVCasReply proto.InternalMessageInfo

func (m *KVCasReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetConfigArgs struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Sandbox              bool     `protobuf:"varint,3,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigArgs) Reset()         { *m = GetConfigArgs{} }
func (m *GetConfigArgs) String() string { return proto.CompactTextString(m) }
func (*GetConfigArgs) ProtoMessage()    {}
func (*GetConfigArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_665b1cce082a77c9, []int{20}
}

func (m *GetConfigArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigArgs.Unmarshal(m, b)
}
func (m *GetConfigArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigArgs.Marshal(b, m, deterministic)
}
func (m *GetConfigArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigArgs.Merge(m, src)
}
func (m *GetConfigArgs) XXX_Size() int {
	return xxx_messageInfo_GetConfigArgs.Size(m)
}
func (m *GetConfigArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigArgs.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigArgs proto.InternalMessageInfo

func (m *GetConfigArgs) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetConfigArgs) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GetConfigArgs) GetSandbox() bool {
	if m != nil {
		return m.Sandbox
	}
	return false
}

type GetConfigReply struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Format               string   `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigReply) Reset()         { *m = GetConfigReply{} }
func (m *GetConfigReply) String() string { return proto.CompactTextString(m) }
func (*GetConfigReply) ProtoMessage()    {}
func (*GetConfigReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_665b1cce082a77c9, []int{21}
}

func (m *GetConfigReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigReply.Unmarshal(m, b)
}
func (m *GetConfigReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigReply.Marshal(b, m, deterministic)
}
func (m *GetConfigReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigReply.Merge(m, src)
}
func (m *GetConfigReply) XXX_Size() int {
	return xxx_messageInfo_GetConfigReply.Size(m)
}
func (m *GetConfigReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigReply proto.InternalMessageInfo

func (m *GetConfigReply) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *GetConfigReply) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

type KVListArgs struct {
	Prefix               string   `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KVListArgs) Reset()         { *m = KVListArgs{} }
func (m *KVListArgs) String() string { return proto.CompactTextString(m) }
func (*KVListArgs) ProtoMessage()    {}
func (*KVListArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_665b1cce082a77c9, []int{22}
}

func (m *KVListArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KVListArgs.Unmarshal(m, b)
}
func (m *KVListArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KVListArgs.Marshal(b, m, deterministic)
}
func (m *KVListArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVListArgs.Merge(m, src)
}
func (m *KVListArgs) XXX_Size() int {
	return xxx_messageInfo_KVListArgs.Size(m)
}
func (m *KVListArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_KVListArgs.DiscardUnknown(m)
}

var xxx_messageInfo_KVListArgs proto.InternalMessageInfo

func (m *KVListArgs) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

type KVListReply struct {
	KvPairs              []*KVPair `protobuf:"bytes,1,rep,name=kvPairs,proto3" json:"kvPairs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *KVListReply) Reset()         { *m = KVListReply{} }
func (m *KVListReply) String() string { return proto.CompactTextString(m) }
func (*KVListReply) ProtoMessage()    {}
func (*KVListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_665b1cce082a77c9, []int{23}
}

func (m *KVListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KVListReply.Unmarshal(m, b)
}
func (m *KVListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KVListReply.Marshal(b, m, deterministic)
}
func (m *KVListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVListReply.Merge(m, src)
}
func (m *KVListReply) XXX_Size() int {
	return xxx_messageInfo_KVListReply.Size(m)
}
func (m *KVListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_KVListReply.DiscardUnknown(m)
}

var xxx_messageInfo_KVListReply proto.InternalMessageInfo

func (m *KVListReply) GetKvPairs() []*KVPair {
	if m != nil {
		return m.KvPairs
	}
	return nil
}

//	// Address is the optional address of the Consul server. The port, if any
//	// will be removed from here and this will be set to the ServerName of the
//	// resulting config.
//	Address string
//
//	// CAFile is the optional path to the CA certificate used for Consul
//	// communication, defaults to the system bundle if not specified.
//	CAFile string
//
//	// CAPath is the optional path to a directory of CA certificates to use for
//	// Consul communication, defaults to the system bundle if not specified.
//	CAPath string
//
//	// CAPem is the optional PEM-encoded CA certificate used for Consul
//	// communication, defaults to the system bundle if not specified.
//	CAPem []byte
//
//	// CertFile is the optional path to the certificate for Consul
//	// communication. If this is set then you need to also set KeyFile.
//	CertFile string
//
//	// CertPEM is the optional PEM-encoded certificate for Consul
//	// communication. If this is set then you need to also set KeyPEM.
//	CertPEM []byte
//
//	// KeyFile is the optional path to the private key for Consul communication.
//	// If this is set then you need to also set CertFile.
//	KeyFile string
//
//	// KeyPEM is the optional PEM-encoded private key for Consul communication.
//	// If this is set then you need to also set CertPEM.
//	KeyPEM []byte
//
//	// InsecureSkipVerify if set to true will disable TLS host verification.
//	InsecureSkipVerify bool
type ConfigTLSConfig struct {
	Address              string   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	CAFile               string   `protobuf:"bytes,2,opt,name=CAFile,proto3" json:"CAFile,omitempty"`
	CAPath               string   `protobuf:"bytes,3,opt,name=CAPath,proto3" json:"CAPath,omitempty"`
	CAPem                []byte   `protobuf:"bytes,4,opt,name=CAPem,proto3" json:"CAPem,omitempty"`
	CertFile             string   `protobuf:"bytes,5,opt,name=CertFile,proto3" json:"CertFile,omitempty"`
	CertPEM              []byte   `protobuf:"bytes,6,opt,name=CertPEM,proto3" json:"CertPEM,omitempty"`
	KeyFile              string   `protobuf:"bytes,7,opt,name=KeyFile,proto3" json:"KeyFile,omitempty"`
	KeyPEM               []byte   `protobuf:"bytes,8,opt,name=KeyPEM,proto3" json:"KeyPEM,omitempty"`
	InsecureSkipVerify   bool     `protobuf:"varint,9,opt,name=InsecureSkipVerify,proto3" json:"InsecureSkipVerify,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigTLSConfig) Reset()         { *m = ConfigTLSConfig{} }
func (m *ConfigTLSConfig) String() string { return proto.CompactTextString(m) }
func (*ConfigTLSConfig) ProtoMessage()    {}
func (*ConfigTLSConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_665b1cce082a77c9, []int{24}
}

func (m *ConfigTLSConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigTLSConfig.Unmarshal(m, b)
}
func (m *ConfigTLSConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigTLSConfig.Marshal(b, m, deterministic)
}
func (m *ConfigTLSConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigTLSConfig.Merge(m, src)
}
func (m *ConfigTLSConfig) XXX_Size() int {
	return xxx_messageInfo_ConfigTLSConfig.Size(m)
}
func (m *ConfigTLSConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigTLSConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigTLSConfig proto.InternalMessageInfo

func (m *ConfigTLSConfig) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ConfigTLSConfig) GetCAFile() string {
	if m != nil {
		return m.CAFile
	}
	return ""
}

func (m *ConfigTLSConfig) GetCAPath() string {
	if m != nil {
		return m.CAPath
	}
	return ""
}

func (m *ConfigTLSConfig) GetCAPem() []byte {
	if m != nil {
		return m.CAPem
	}
	return nil
}

func (m *ConfigTLSConfig) GetCertFile() string {
	if m != nil {
		return m.CertFile
	}
	return ""
}

func (m *ConfigTLSConfig) GetCertPEM() []byte {
	if m != nil {
		return m.CertPEM
	}
	return nil
}

func (m *ConfigTLSConfig) GetKeyFile() string {
	if m != nil {
		return m.KeyFile
	}
	return ""
}

func (m *ConfigTLSConfig) GetKeyPEM() []byte {
	if m != nil {
		return m.KeyPEM
	}
	return nil
}

func (m *ConfigTLSConfig) GetInsecureSkipVerify() bool {
	if m != nil {
		return m.InsecureSkipVerify
	}
	return false
}

type ConfigApplication struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Profile              string   `protobuf:"bytes,2,opt,name=Profile,proto3" json:"Profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigApplication) Reset()         { *m = ConfigApplication{} }
func (m *ConfigApplication) String() string { return proto.CompactTextString(m) }
func (*ConfigApplication) ProtoMessage()    {}
func (*ConfigApplication) Descriptor() ([]byte, []int) {
	return fileDescriptor_665b1cce082a77c9, []int{25}
}

func (m *ConfigApplication) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigApplication.Unmarshal(m, b)
}
func (m *ConfigApplication) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigApplication.Marshal(b, m, deterministic)
}
func (m *ConfigApplication) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigApplication.Merge(m, src)
}
func (m *ConfigApplication) XXX_Size() int {
	return xxx_messageInfo_ConfigApplication.Size(m)
}
func (m *ConfigApplication) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigApplication.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigApplication proto.InternalMessageInfo

func (m *ConfigApplication) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ConfigApplication) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

type ConfigConfig struct {
	DataKey              string   `protobuf:"bytes,1,opt,name=DataKey,proto3" json:"DataKey,omitempty"`
	Format               string   `protobuf:"bytes,2,opt,name=Format,proto3" json:"Format,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigConfig) Reset()         { *m = ConfigConfig{} }
func (m *ConfigConfig) String() string { return proto.CompactTextString(m) }
func (*ConfigConfig) ProtoMessage()    {}
func (*ConfigConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_665b1cce082a77c9, []int{26}
}

func (m *ConfigConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigConfig.Unmarshal(m, b)
}
func (m *ConfigConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigConfig.Marshal(b, m, deterministic)
}
func (m *ConfigConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigConfig.Merge(m, src)
}
func (m *ConfigConfig) XXX_Size() int {
	return xxx_messageInfo_ConfigConfig.Size(m)
}
func (m *ConfigConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigConfig proto.InternalMessageInfo

func (m *ConfigConfig) GetDataKey() string {
	if m != nil {
		return m.DataKey
	}
	return ""
}

func (m *ConfigConfig) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

type ConfigReply struct {
	Datacenter           string             `protobuf:"bytes,1,opt,name=Datacenter,proto3" json:"Datacenter,omitempty"`
	ZoneAddress          string             `protobuf:"bytes,2,opt,name=ZoneAddress,proto3" json:"ZoneAddress,omitempty"`
	Token                string             `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty"`
	Application          *ConfigApplication `protobuf:"bytes,4,opt,name=Application,proto3" json:"Application,omitempty"`
	Config               *ConfigConfig      `protobuf:"bytes,5,opt,name=Config,proto3" json:"Config,omitempty"`
	TLSConfig            *ConfigTLSConfig   `protobuf:"bytes,6,opt,name=TLSConfig,proto3" json:"TLSConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ConfigReply) Reset()         { *m = ConfigReply{} }
func (m *ConfigReply) String() string { return proto.CompactTextString(m) }
func (*ConfigReply) ProtoMessage()    {}
func (*ConfigReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_665b1cce082a77c9, []int{27}
}

func (m *ConfigReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigReply.Unmarshal(m, b)
}
func (m *ConfigReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigReply.Marshal(b, m, deterministic)
}
func (m *ConfigReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigReply.Merge(m, src)
}
func (m *ConfigReply) XXX_Size() int {
	return xxx_messageInfo_ConfigReply.Size(m)
}
func (m *ConfigReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigReply.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigReply proto.InternalMessageInfo

func (m *ConfigReply) GetDatacenter() string {
	if m != nil {
		return m.Datacenter
	}
	return ""
}

func (m *ConfigReply) GetZoneAddress() string {
	if m != nil {
		return m.ZoneAddress
	}
	return ""
}

func (m *ConfigReply) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ConfigReply) GetApplication() *ConfigApplication {
	if m != nil {
		return m.Application
	}
	return nil
}

func (m *ConfigReply) GetConfig() *ConfigConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *ConfigReply) GetTLSConfig() *ConfigTLSConfig {
	if m != nil {
		return m.TLSConfig
	}
	return nil
}

func init() {
	proto.RegisterType((*ConsulEmpty)(nil), "proto.ConsulEmpty")
	proto.RegisterType((*AgentWeights)(nil), "proto.AgentWeights")
	proto.RegisterType((*ServiceAddress)(nil), "proto.ServiceAddress")
	proto.RegisterType((*GetServiceArgs)(nil), "proto.GetServiceArgs")
	proto.RegisterType((*GetServiceReply)(nil), "proto.GetServiceReply")
	proto.RegisterMapType((map[string]string)(nil), "proto.GetServiceReply.MetaEntry")
	proto.RegisterMapType((map[string]*ServiceAddress)(nil), "proto.GetServiceReply.TaggedAddressesEntry")
	proto.RegisterType((*NewSessionArgs)(nil), "proto.NewSessionArgs")
	proto.RegisterType((*ServiceCheck)(nil), "proto.ServiceCheck")
	proto.RegisterType((*SessionEntry)(nil), "proto.SessionEntry")
	proto.RegisterType((*NewSessionReply)(nil), "proto.NewSessionReply")
	proto.RegisterType((*SessionInfoArgs)(nil), "proto.SessionInfoArgs")
	proto.RegisterType((*SessionInfoReply)(nil), "proto.SessionInfoReply")
	proto.RegisterType((*DestroySessionArgs)(nil), "proto.DestroySessionArgs")
	proto.RegisterType((*KVPair)(nil), "proto.KVPair")
	proto.RegisterType((*KVAcquireArgs)(nil), "proto.KVAcquireArgs")
	proto.RegisterType((*KVAcquireReply)(nil), "proto.KVAcquireReply")
	proto.RegisterType((*KVReleaseArgs)(nil), "proto.KVReleaseArgs")
	proto.RegisterType((*KVInfoArgs)(nil), "proto.KVInfoArgs")
	proto.RegisterType((*KVInfoReply)(nil), "proto.KVInfoReply")
	proto.RegisterType((*KVCasArgs)(nil), "proto.KVCasArgs")
	proto.RegisterType((*KVCasReply)(nil), "proto.KVCasReply")
	proto.RegisterType((*GetConfigArgs)(nil), "proto.GetConfigArgs")
	proto.RegisterType((*GetConfigReply)(nil), "proto.GetConfigReply")
	proto.RegisterType((*KVListArgs)(nil), "proto.KVListArgs")
	proto.RegisterType((*KVListReply)(nil), "proto.KVListReply")
	proto.RegisterType((*ConfigTLSConfig)(nil), "proto.ConfigTLSConfig")
	proto.RegisterType((*ConfigApplication)(nil), "proto.ConfigApplication")
	proto.RegisterType((*ConfigConfig)(nil), "proto.ConfigConfig")
	proto.RegisterType((*ConfigReply)(nil), "proto.ConfigReply")
}

func init() {
	proto.RegisterFile("consul.proto", fileDescriptor_665b1cce082a77c9)
}

var fileDescriptor_665b1cce082a77c9 = []byte{
	// 1323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xdb, 0x72, 0xdb, 0x44,
	0x18, 0x1e, 0xcb, 0x87, 0xd8, 0xbf, 0x72, 0xdc, 0xb6, 0x41, 0x78, 0x98, 0x8e, 0xab, 0x69, 0x21,
	0xd0, 0x12, 0x3a, 0xa6, 0x40, 0x69, 0xa1, 0xe0, 0x3a, 0x6d, 0xc9, 0x38, 0x29, 0x19, 0x25, 0x35,
	0x43, 0xef, 0x36, 0xd6, 0xda, 0xd1, 0xd8, 0x91, 0x8c, 0xa4, 0xb8, 0xf5, 0x3d, 0x37, 0x5c, 0xf1,
	0x18, 0xbc, 0x07, 0x4f, 0xc3, 0x63, 0x30, 0xff, 0xee, 0xbf, 0xd2, 0xca, 0x76, 0x06, 0xae, 0xb4,
	0xff, 0xf9, 0xb8, 0xdf, 0x0a, 0xd6, 0x07, 0x51, 0x98, 0x5c, 0x4d, 0xf6, 0xa7, 0x71, 0x94, 0x46,
	0xac, 0x2a, 0x3f, 0xee, 0x06, 0xd8, 0x5d, 0xc9, 0x7e, 0x71, 0x39, 0x4d, 0xe7, 0xee, 0x73, 0x58,
	0xef, 0x8c, 0x44, 0x98, 0xfe, 0x22, 0x82, 0xd1, 0x45, 0x9a, 0x30, 0x07, 0xd6, 0xa6, 0x3c, 0x49,
	0x82, 0x70, 0xe4, 0x94, 0x5a, 0xa5, 0xbd, 0xaa, 0xa7, 0x49, 0x94, 0xbc, 0xe3, 0x71, 0x88, 0x12,
	0x4b, 0x49, 0x88, 0x74, 0x9f, 0xc1, 0xe6, 0xa9, 0x88, 0x67, 0xc1, 0x40, 0x74, 0x7c, 0x3f, 0x16,
	0x89, 0xf4, 0xc2, 0xd5, 0x51, 0x7a, 0x69, 0x78, 0x9a, 0x64, 0x0c, 0x2a, 0xd3, 0x28, 0x4e, 0xc9,
	0x85, 0x3c, 0xbb, 0x8f, 0x61, 0xf3, 0x95, 0x48, 0xb5, 0x8b, 0x78, 0x24, 0xb5, 0x42, 0x7e, 0x29,
	0xc8, 0x58, 0x9e, 0x91, 0x97, 0xf2, 0x51, 0x22, 0x2d, 0x1b, 0x9e, 0x3c, 0xbb, 0x7f, 0x56, 0x60,
	0x2b, 0x37, 0xf5, 0xc4, 0x74, 0x32, 0x47, 0xbd, 0x71, 0x10, 0xfa, 0xda, 0x16, 0xcf, 0x6c, 0x13,
	0xac, 0xc0, 0x27, 0x4b, 0x2b, 0xf0, 0x31, 0xbf, 0x44, 0xd9, 0x38, 0x65, 0x95, 0x1f, 0x91, 0x59,
	0x94, 0x4a, 0xab, 0xac, 0xa3, 0xb0, 0x47, 0x50, 0xb9, 0x14, 0x29, 0x77, 0xaa, 0xad, 0xf2, 0x9e,
	0xdd, 0x6e, 0xa9, 0x7e, 0xee, 0x2f, 0xc4, 0xdd, 0x3f, 0x16, 0x29, 0x7f, 0x11, 0xa6, 0xf1, 0xdc,
	0x93, 0xda, 0x59, 0xa5, 0xb5, 0xbc, 0x52, 0xb3, 0x2f, 0x6b, 0xc5, 0xbe, 0xbc, 0x81, 0xad, 0x94,
	0x8f, 0x46, 0xc2, 0xa7, 0x16, 0x8a, 0xc4, 0xa9, 0xcb, 0x70, 0xf7, 0xaf, 0x09, 0x77, 0x56, 0xd4,
	0x56, 0x91, 0x17, 0x7d, 0xb0, 0xcf, 0x61, 0x8d, 0x26, 0xeb, 0x34, 0x5a, 0xa5, 0x3d, 0xbb, 0x7d,
	0x83, 0xdc, 0x99, 0x43, 0xf7, 0xb4, 0x0e, 0x7b, 0x00, 0x3b, 0x22, 0xe4, 0xe7, 0x13, 0x71, 0xc6,
	0x47, 0x3f, 0xcf, 0x44, 0x1c, 0x07, 0xbe, 0x70, 0xa0, 0x55, 0xda, 0xab, 0x7b, 0xcb, 0x82, 0xe6,
	0x37, 0xd0, 0xc8, 0x8a, 0x66, 0xdb, 0x50, 0x1e, 0x8b, 0x39, 0x75, 0x1d, 0x8f, 0xec, 0x26, 0x54,
	0x67, 0x7c, 0x72, 0x25, 0xa8, 0xef, 0x8a, 0x78, 0x62, 0x3d, 0x2e, 0x35, 0x7f, 0x85, 0x9b, 0xab,
	0xd2, 0x5f, 0xe1, 0xe3, 0xbe, 0xe9, 0xc3, 0x6e, 0xdf, 0xa2, 0xec, 0x8b, 0xeb, 0x66, 0xb8, 0x76,
	0x3d, 0xd8, 0x7c, 0x2d, 0xde, 0x9d, 0x8a, 0x24, 0x09, 0xa2, 0xf0, 0xda, 0x5d, 0xda, 0x86, 0x72,
	0x9a, 0x4e, 0x28, 0x31, 0x3c, 0xb2, 0x26, 0xd4, 0xcf, 0xc5, 0x05, 0x9f, 0x05, 0x51, 0x4c, 0x2b,
	0x91, 0xd1, 0xee, 0x77, 0xb0, 0x4e, 0x01, 0xbb, 0x17, 0x62, 0x30, 0xc6, 0x6d, 0x3a, 0x3c, 0x20,
	0x7f, 0xd6, 0xe1, 0x01, 0xfb, 0x08, 0x1a, 0xaf, 0xf9, 0xa5, 0x48, 0xa6, 0x7c, 0xa0, 0x8b, 0xcd,
	0x19, 0xee, 0x5f, 0x16, 0x9a, 0xcb, 0x7c, 0x54, 0x95, 0x2d, 0xb0, 0xbb, 0xb1, 0xe0, 0xa9, 0x38,
	0x0c, 0x7d, 0xf1, 0x5e, 0xfa, 0xa9, 0x78, 0x26, 0x8b, 0x02, 0x58, 0x59, 0x00, 0x06, 0x15, 0xf4,
	0x47, 0x89, 0xc9, 0xb3, 0xe4, 0x45, 0xbe, 0x70, 0x2a, 0xc4, 0x8b, 0x7c, 0x81, 0x89, 0x1c, 0x45,
	0x83, 0xf1, 0x81, 0x98, 0xf0, 0xb9, 0x53, 0x55, 0x89, 0x64, 0x0c, 0x2c, 0xf1, 0xb9, 0x2e, 0xb1,
	0xa6, 0x4a, 0xd4, 0x34, 0x36, 0xe4, 0xec, 0xec, 0x88, 0x96, 0x12, 0x8f, 0x6c, 0x17, 0x6a, 0xb2,
	0x5a, 0xb5, 0x87, 0x0d, 0x8f, 0x28, 0x76, 0x1b, 0x00, 0x63, 0x91, 0xac, 0x21, 0x65, 0x06, 0x87,
	0x7d, 0x0b, 0x1b, 0x66, 0xb3, 0x12, 0x07, 0xe4, 0x1a, 0xdf, 0x28, 0x4e, 0x4e, 0xca, 0xbc, 0xa2,
	0xa6, 0x7b, 0x0f, 0xb6, 0xf2, 0xd9, 0x65, 0x97, 0x79, 0x71, 0x78, 0xee, 0x1d, 0xd8, 0x22, 0x9d,
	0xc3, 0x70, 0x18, 0xc9, 0x19, 0xab, 0xfb, 0x5d, 0xd2, 0xf7, 0xdb, 0xfd, 0x1e, 0xb6, 0x0d, 0x15,
	0xe5, 0xea, 0x53, 0xa8, 0x0a, 0xec, 0xbf, 0x54, 0x33, 0x13, 0xca, 0x47, 0xe3, 0x29, 0x0d, 0xf7,
	0x2e, 0xb0, 0x03, 0x91, 0xa4, 0x71, 0x34, 0x37, 0x17, 0x69, 0x31, 0xc8, 0xdf, 0x25, 0xa8, 0xf5,
	0xfa, 0x27, 0x3c, 0x90, 0xed, 0xeb, 0xe5, 0x8b, 0xdb, 0x13, 0x4b, 0x43, 0xb6, 0x96, 0x87, 0xdc,
	0x02, 0xfb, 0x38, 0xf2, 0x83, 0xe1, 0x5c, 0x69, 0x94, 0x95, 0x86, 0xc1, 0xd2, 0xe3, 0x54, 0xf2,
	0x8a, 0x94, 0xe7, 0x0c, 0xbc, 0x5e, 0x2f, 0x27, 0x08, 0x55, 0x55, 0x29, 0x51, 0x04, 0x72, 0xfb,
	0xf2, 0xc2, 0xe0, 0x84, 0xd7, 0x3d, 0x45, 0x20, 0xee, 0x50, 0x25, 0x1a, 0x77, 0x88, 0x74, 0x9f,
	0xc2, 0x46, 0xaf, 0xdf, 0x19, 0xfc, 0x76, 0x15, 0xc4, 0x0a, 0x7a, 0x97, 0xef, 0xa0, 0x04, 0x4b,
	0x65, 0x6c, 0x69, 0xb0, 0x54, 0xc6, 0x9f, 0xc1, 0x66, 0x66, 0xac, 0x9a, 0x8c, 0xba, 0x57, 0x83,
	0x81, 0x06, 0xfe, 0xba, 0xa7, 0x49, 0xf7, 0x0e, 0x06, 0xf2, 0xc4, 0x44, 0xf0, 0xe4, 0x9a, 0x40,
	0xee, 0x6d, 0x80, 0x5e, 0x3f, 0x9b, 0xe9, 0xb2, 0xfc, 0x11, 0xd8, 0x4a, 0xae, 0x62, 0xdd, 0x83,
	0xda, 0x78, 0x36, 0xe5, 0x41, 0x4c, 0x13, 0xdd, 0xa0, 0x89, 0xaa, 0x99, 0x78, 0x24, 0x74, 0xdb,
	0xd0, 0xe8, 0xf5, 0xbb, 0x3c, 0x91, 0x4e, 0xff, 0xa7, 0xcd, 0xc7, 0x98, 0x49, 0x97, 0x27, 0xff,
	0x55, 0xd4, 0x1b, 0xd8, 0x78, 0x25, 0xd2, 0x6e, 0x14, 0x0e, 0x83, 0xd1, 0xf5, 0xdd, 0x9b, 0x89,
	0xd8, 0xec, 0x1e, 0x91, 0xd2, 0x2d, 0x0f, 0xfd, 0xf3, 0x48, 0x0d, 0x1f, 0xdd, 0x2a, 0x12, 0x1f,
	0xd4, 0xcc, 0xad, 0x4a, 0x21, 0xc3, 0xd2, 0x92, 0x1a, 0xab, 0x24, 0xf0, 0x8e, 0x0e, 0xa3, 0xf8,
	0x92, 0xa7, 0xe4, 0x9a, 0x28, 0xf7, 0x2e, 0xa6, 0x7f, 0x14, 0x24, 0xa9, 0xcc, 0x69, 0x17, 0x6a,
	0xd3, 0x58, 0x0c, 0x83, 0xf7, 0x94, 0x16, 0x51, 0xee, 0xd7, 0xd8, 0x4e, 0xd4, 0x52, 0x21, 0x3e,
	0x81, 0xb5, 0xf1, 0x0c, 0xbb, 0x80, 0x55, 0x96, 0x97, 0x7b, 0xa3, 0xa5, 0xee, 0x1f, 0x16, 0x6c,
	0xa9, 0xdc, 0xce, 0x8e, 0x4e, 0xd5, 0x01, 0x6b, 0xe9, 0x14, 0x1f, 0x7c, 0xfd, 0x2b, 0x80, 0x38,
	0xd2, 0x79, 0x19, 0x4c, 0x34, 0x32, 0x12, 0xa5, 0xf8, 0x27, 0x3c, 0xbd, 0x20, 0x54, 0x23, 0x0a,
	0x2b, 0xed, 0x76, 0x4e, 0xc4, 0xa5, 0x5c, 0xf8, 0x75, 0x4f, 0x11, 0x88, 0x5d, 0x5d, 0x11, 0xa7,
	0xd2, 0x8f, 0x02, 0xb6, 0x8c, 0xc6, 0xd8, 0x78, 0x3e, 0x79, 0x71, 0x4c, 0x4b, 0xaf, 0x49, 0x94,
	0xf4, 0xc4, 0x5c, 0x1a, 0xd1, 0xda, 0x13, 0x89, 0xd1, 0x7b, 0x62, 0x8e, 0x26, 0x75, 0x69, 0x42,
	0x14, 0xdb, 0x07, 0x76, 0x18, 0x26, 0x62, 0x70, 0x15, 0x8b, 0xd3, 0x71, 0x30, 0xed, 0x8b, 0x38,
	0x18, 0xce, 0xe5, 0xd3, 0x59, 0xf7, 0x56, 0x48, 0xdc, 0x0e, 0xec, 0xd0, 0xf4, 0xa7, 0xd3, 0x49,
	0x30, 0xe0, 0x29, 0x0e, 0x56, 0xc3, 0x75, 0xc9, 0x80, 0x6b, 0x07, 0xd6, 0x4e, 0xe2, 0x68, 0x98,
	0xf7, 0x41, 0x93, 0xee, 0x8f, 0xb0, 0xae, 0x5c, 0xe4, 0xad, 0x3c, 0xe0, 0x29, 0xcf, 0xf1, 0x44,
	0x93, 0x98, 0xf4, 0xcb, 0xc2, 0xb8, 0x15, 0xe5, 0xfe, 0x6e, 0xc9, 0x7f, 0xba, 0x6c, 0x59, 0x6e,
	0x03, 0xa0, 0xc9, 0x40, 0x84, 0xa9, 0x88, 0xc9, 0x89, 0xc1, 0x41, 0xe4, 0x79, 0x1b, 0x85, 0xfa,
	0xf5, 0x24, 0x67, 0x26, 0x0b, 0x87, 0x70, 0x16, 0x8d, 0x45, 0x48, 0xb3, 0x51, 0x04, 0x7b, 0x02,
	0xb6, 0x51, 0xa6, 0x1c, 0x90, 0xdd, 0x76, 0x68, 0x4b, 0x96, 0xda, 0xe0, 0x99, 0xca, 0xec, 0x3e,
	0xd4, 0x94, 0x86, 0x1c, 0x5f, 0x0e, 0xbf, 0x66, 0xe9, 0x1e, 0xa9, 0xb0, 0x47, 0xd0, 0xc8, 0x56,
	0x4b, 0xce, 0xd4, 0x6e, 0xef, 0x16, 0xf4, 0x33, 0xa9, 0x97, 0x2b, 0xb6, 0xff, 0xa9, 0xc8, 0x18,
	0xc9, 0xd5, 0x84, 0x3d, 0xd4, 0xd1, 0x18, 0xcb, 0xed, 0xf4, 0x3f, 0x6f, 0x93, 0x15, 0x7c, 0xa9,
	0x9e, 0x3d, 0x05, 0xc8, 0xff, 0xb0, 0xd8, 0xad, 0xa5, 0x9f, 0x2e, 0xbc, 0x49, 0xcd, 0xdd, 0xd5,
	0xff, 0x62, 0x68, 0x9c, 0x3f, 0x5c, 0x99, 0x71, 0xf1, 0x3f, 0x24, 0x33, 0x5e, 0x7c, 0xe2, 0x9e,
	0x81, 0x6d, 0xbc, 0x55, 0x6c, 0xb7, 0xf8, 0x2e, 0x69, 0x38, 0x6c, 0x7e, 0xb0, 0xcc, 0x57, 0xf6,
	0x3f, 0xc0, 0x66, 0xf1, 0xb1, 0x62, 0x1f, 0x92, 0xea, 0xf2, 0x1b, 0xd6, 0x5c, 0xd1, 0x0e, 0xf6,
	0x18, 0x01, 0x92, 0x50, 0x9c, 0xdd, 0xcc, 0x2e, 0xbd, 0xf1, 0x28, 0x34, 0x6f, 0x2d, 0x72, 0x55,
	0xe8, 0xaf, 0xd0, 0x92, 0x30, 0xdd, 0xb0, 0x34, 0x50, 0x7e, 0x65, 0xc0, 0x2f, 0xf0, 0xdd, 0x94,
	0xc5, 0xee, 0x64, 0x36, 0x59, 0x9d, 0xac, 0xc0, 0x52, 0x71, 0x1e, 0x40, 0x55, 0xc2, 0x31, 0xdb,
	0xce, 0x84, 0x04, 0xe8, 0xcd, 0x1d, 0x93, 0xa3, 0xb4, 0x1f, 0x42, 0xbd, 0xd7, 0x57, 0x2f, 0xed,
	0x0a, 0x83, 0x6b, 0x13, 0x42, 0x24, 0x34, 0x12, 0xd2, 0xf0, 0x69, 0x24, 0x94, 0x61, 0xe5, 0x73,
	0xfb, 0x27, 0xeb, 0xed, 0xda, 0xfe, 0x53, 0x29, 0x38, 0xaf, 0xc9, 0xcf, 0x97, 0xff, 0x06, 0x00,
	0x00, 0xff, 0xff, 0xc7, 0x6c, 0xfe, 0x33, 0x6f, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ConsulClient is the client API for Consul service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConsulClient interface {
	Config(ctx context.Context, in *ConsulEmpty, opts ...grpc.CallOption) (*ConfigReply, error)
	GetService(ctx context.Context, in *GetServiceArgs, opts ...grpc.CallOption) (*GetServiceReply, error)
	NewSession(ctx context.Context, in *NewSessionArgs, opts ...grpc.CallOption) (*NewSessionReply, error)
	SessionInfo(ctx context.Context, in *SessionInfoArgs, opts ...grpc.CallOption) (*SessionInfoReply, error)
	DestroySession(ctx context.Context, in *DestroySessionArgs, opts ...grpc.CallOption) (*ConsulEmpty, error)
	//对一个kv进行加锁
	//another标志key是否被其它session锁定
	//err==nil && false == another 加锁成功
	KVAcquire(ctx context.Context, in *KVAcquireArgs, opts ...grpc.CallOption) (*KVAcquireReply, error)
	//释放一个session的锁
	KVRelease(ctx context.Context, in *KVReleaseArgs, opts ...grpc.CallOption) (*ConsulEmpty, error)
	//获取kv信息
	KVInfo(ctx context.Context, in *KVInfoArgs, opts ...grpc.CallOption) (*KVInfoReply, error)
	//检查或者设置key
	KVCas(ctx context.Context, in *KVCasArgs, opts ...grpc.CallOption) (*KVCasReply, error)
	KVCreate(ctx context.Context, in *KVCasArgs, opts ...grpc.CallOption) (*ConsulEmpty, error)
	KVList(ctx context.Context, in *KVListArgs, opts ...grpc.CallOption) (*KVListReply, error)
}

type consulClient struct {
	cc grpc.ClientConnInterface
}

func NewConsulClient(cc grpc.ClientConnInterface) ConsulClient {
	return &consulClient{cc}
}

func (c *consulClient) Config(ctx context.Context, in *ConsulEmpty, opts ...grpc.CallOption) (*ConfigReply, error) {
	out := new(ConfigReply)
	err := c.cc.Invoke(ctx, "/proto.Consul/Config", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consulClient) GetService(ctx context.Context, in *GetServiceArgs, opts ...grpc.CallOption) (*GetServiceReply, error) {
	out := new(GetServiceReply)
	err := c.cc.Invoke(ctx, "/proto.Consul/GetService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consulClient) NewSession(ctx context.Context, in *NewSessionArgs, opts ...grpc.CallOption) (*NewSessionReply, error) {
	out := new(NewSessionReply)
	err := c.cc.Invoke(ctx, "/proto.Consul/NewSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consulClient) SessionInfo(ctx context.Context, in *SessionInfoArgs, opts ...grpc.CallOption) (*SessionInfoReply, error) {
	out := new(SessionInfoReply)
	err := c.cc.Invoke(ctx, "/proto.Consul/SessionInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consulClient) DestroySession(ctx context.Context, in *DestroySessionArgs, opts ...grpc.CallOption) (*ConsulEmpty, error) {
	out := new(ConsulEmpty)
	err := c.cc.Invoke(ctx, "/proto.Consul/DestroySession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consulClient) KVAcquire(ctx context.Context, in *KVAcquireArgs, opts ...grpc.CallOption) (*KVAcquireReply, error) {
	out := new(KVAcquireReply)
	err := c.cc.Invoke(ctx, "/proto.Consul/KVAcquire", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consulClient) KVRelease(ctx context.Context, in *KVReleaseArgs, opts ...grpc.CallOption) (*ConsulEmpty, error) {
	out := new(ConsulEmpty)
	err := c.cc.Invoke(ctx, "/proto.Consul/KVRelease", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consulClient) KVInfo(ctx context.Context, in *KVInfoArgs, opts ...grpc.CallOption) (*KVInfoReply, error) {
	out := new(KVInfoReply)
	err := c.cc.Invoke(ctx, "/proto.Consul/KVInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consulClient) KVCas(ctx context.Context, in *KVCasArgs, opts ...grpc.CallOption) (*KVCasReply, error) {
	out := new(KVCasReply)
	err := c.cc.Invoke(ctx, "/proto.Consul/KVCas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consulClient) KVCreate(ctx context.Context, in *KVCasArgs, opts ...grpc.CallOption) (*ConsulEmpty, error) {
	out := new(ConsulEmpty)
	err := c.cc.Invoke(ctx, "/proto.Consul/KVCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consulClient) KVList(ctx context.Context, in *KVListArgs, opts ...grpc.CallOption) (*KVListReply, error) {
	out := new(KVListReply)
	err := c.cc.Invoke(ctx, "/proto.Consul/KVList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsulServer is the server API for Consul service.
type ConsulServer interface {
	Config(context.Context, *ConsulEmpty) (*ConfigReply, error)
	GetService(context.Context, *GetServiceArgs) (*GetServiceReply, error)
	NewSession(context.Context, *NewSessionArgs) (*NewSessionReply, error)
	SessionInfo(context.Context, *SessionInfoArgs) (*SessionInfoReply, error)
	DestroySession(context.Context, *DestroySessionArgs) (*ConsulEmpty, error)
	//对一个kv进行加锁
	//another标志key是否被其它session锁定
	//err==nil && false == another 加锁成功
	KVAcquire(context.Context, *KVAcquireArgs) (*KVAcquireReply, error)
	//释放一个session的锁
	KVRelease(context.Context, *KVReleaseArgs) (*ConsulEmpty, error)
	//获取kv信息
	KVInfo(context.Context, *KVInfoArgs) (*KVInfoReply, error)
	//检查或者设置key
	KVCas(context.Context, *KVCasArgs) (*KVCasReply, error)
	KVCreate(context.Context, *KVCasArgs) (*ConsulEmpty, error)
	KVList(context.Context, *KVListArgs) (*KVListReply, error)
}

// UnimplementedConsulServer can be embedded to have forward compatible implementations.
type UnimplementedConsulServer struct {
}

func (*UnimplementedConsulServer) Config(ctx context.Context, req *ConsulEmpty) (*ConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Config not implemented")
}
func (*UnimplementedConsulServer) GetService(ctx context.Context, req *GetServiceArgs) (*GetServiceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetService not implemented")
}
func (*UnimplementedConsulServer) NewSession(ctx context.Context, req *NewSessionArgs) (*NewSessionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewSession not implemented")
}
func (*UnimplementedConsulServer) SessionInfo(ctx context.Context, req *SessionInfoArgs) (*SessionInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SessionInfo not implemented")
}
func (*UnimplementedConsulServer) DestroySession(ctx context.Context, req *DestroySessionArgs) (*ConsulEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroySession not implemented")
}
func (*UnimplementedConsulServer) KVAcquire(ctx context.Context, req *KVAcquireArgs) (*KVAcquireReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KVAcquire not implemented")
}
func (*UnimplementedConsulServer) KVRelease(ctx context.Context, req *KVReleaseArgs) (*ConsulEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KVRelease not implemented")
}
func (*UnimplementedConsulServer) KVInfo(ctx context.Context, req *KVInfoArgs) (*KVInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KVInfo not implemented")
}
func (*UnimplementedConsulServer) KVCas(ctx context.Context, req *KVCasArgs) (*KVCasReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KVCas not implemented")
}
func (*UnimplementedConsulServer) KVCreate(ctx context.Context, req *KVCasArgs) (*ConsulEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KVCreate not implemented")
}
func (*UnimplementedConsulServer) KVList(ctx context.Context, req *KVListArgs) (*KVListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KVList not implemented")
}

func RegisterConsulServer(s *grpc.Server, srv ConsulServer) {
	s.RegisterService(&_Consul_serviceDesc, srv)
}

func _Consul_Config_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsulEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsulServer).Config(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Consul/Config",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsulServer).Config(ctx, req.(*ConsulEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Consul_GetService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsulServer).GetService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Consul/GetService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsulServer).GetService(ctx, req.(*GetServiceArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Consul_NewSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewSessionArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsulServer).NewSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Consul/NewSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsulServer).NewSession(ctx, req.(*NewSessionArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Consul_SessionInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionInfoArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsulServer).SessionInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Consul/SessionInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsulServer).SessionInfo(ctx, req.(*SessionInfoArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Consul_DestroySession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroySessionArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsulServer).DestroySession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Consul/DestroySession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsulServer).DestroySession(ctx, req.(*DestroySessionArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Consul_KVAcquire_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVAcquireArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsulServer).KVAcquire(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Consul/KVAcquire",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsulServer).KVAcquire(ctx, req.(*KVAcquireArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Consul_KVRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVReleaseArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsulServer).KVRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Consul/KVRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsulServer).KVRelease(ctx, req.(*KVReleaseArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Consul_KVInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVInfoArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsulServer).KVInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Consul/KVInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsulServer).KVInfo(ctx, req.(*KVInfoArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Consul_KVCas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVCasArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsulServer).KVCas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Consul/KVCas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsulServer).KVCas(ctx, req.(*KVCasArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Consul_KVCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVCasArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsulServer).KVCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Consul/KVCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsulServer).KVCreate(ctx, req.(*KVCasArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Consul_KVList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVListArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsulServer).KVList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Consul/KVList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsulServer).KVList(ctx, req.(*KVListArgs))
	}
	return interceptor(ctx, in, info, handler)
}

var _Consul_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Consul",
	HandlerType: (*ConsulServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Config",
			Handler:    _Consul_Config_Handler,
		},
		{
			MethodName: "GetService",
			Handler:    _Consul_GetService_Handler,
		},
		{
			MethodName: "NewSession",
			Handler:    _Consul_NewSession_Handler,
		},
		{
			MethodName: "SessionInfo",
			Handler:    _Consul_SessionInfo_Handler,
		},
		{
			MethodName: "DestroySession",
			Handler:    _Consul_DestroySession_Handler,
		},
		{
			MethodName: "KVAcquire",
			Handler:    _Consul_KVAcquire_Handler,
		},
		{
			MethodName: "KVRelease",
			Handler:    _Consul_KVRelease_Handler,
		},
		{
			MethodName: "KVInfo",
			Handler:    _Consul_KVInfo_Handler,
		},
		{
			MethodName: "KVCas",
			Handler:    _Consul_KVCas_Handler,
		},
		{
			MethodName: "KVCreate",
			Handler:    _Consul_KVCreate_Handler,
		},
		{
			MethodName: "KVList",
			Handler:    _Consul_KVList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "consul.proto",
}
