// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SchemaRequestArgs struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchemaRequestArgs) Reset()         { *m = SchemaRequestArgs{} }
func (m *SchemaRequestArgs) String() string { return proto.CompactTextString(m) }
func (*SchemaRequestArgs) ProtoMessage()    {}
func (*SchemaRequestArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{0}
}

func (m *SchemaRequestArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemaRequestArgs.Unmarshal(m, b)
}
func (m *SchemaRequestArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemaRequestArgs.Marshal(b, m, deterministic)
}
func (m *SchemaRequestArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemaRequestArgs.Merge(m, src)
}
func (m *SchemaRequestArgs) XXX_Size() int {
	return xxx_messageInfo_SchemaRequestArgs.Size(m)
}
func (m *SchemaRequestArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemaRequestArgs.DiscardUnknown(m)
}

var xxx_messageInfo_SchemaRequestArgs proto.InternalMessageInfo

//接口属性列
//type Field struct {
//    Field      string `json:"field"`
//    Name       string `json:"name"`
//    Type       string `json:"type"`
//    Required   bool   `json:"required"`
//    Deprecated bool   `json:"deprecated"`
//}
type Field struct {
	Field                string   `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind                 string   `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Required             bool     `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	Deprecated           bool     `protobuf:"varint,5,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	IsList               bool     `protobuf:"varint,6,opt,name=isList,proto3" json:"isList,omitempty"`
	Example              string   `protobuf:"bytes,8,opt,name=example,proto3" json:"example,omitempty"`
	Reference            []*Field `protobuf:"bytes,9,rep,name=reference,proto3" json:"reference,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{1}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *Field) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Field) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Field) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

func (m *Field) GetDeprecated() bool {
	if m != nil {
		return m.Deprecated
	}
	return false
}

func (m *Field) GetIsList() bool {
	if m != nil {
		return m.IsList
	}
	return false
}

func (m *Field) GetExample() string {
	if m != nil {
		return m.Example
	}
	return ""
}

func (m *Field) GetReference() []*Field {
	if m != nil {
		return m.Reference
	}
	return nil
}

////接口属性
//type Schema struct {
//	Description string   `json:"description"`
//	Authorized  bool     `json:"authorized"`
//	Deprecated  bool     `json:"deprecated"`
//	Input       []*Field `json:"input,omitempty"`
//	Output      []*Field `json:"output,omitempty"`
//}
type Schema struct {
	Description          string   `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Authorized           bool     `protobuf:"varint,2,opt,name=authorized,proto3" json:"authorized,omitempty"`
	Deprecated           bool     `protobuf:"varint,3,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	Input                []*Field `protobuf:"bytes,4,rep,name=input,proto3" json:"input,omitempty"`
	Output               []*Field `protobuf:"bytes,5,rep,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Schema) Reset()         { *m = Schema{} }
func (m *Schema) String() string { return proto.CompactTextString(m) }
func (*Schema) ProtoMessage()    {}
func (*Schema) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{2}
}

func (m *Schema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schema.Unmarshal(m, b)
}
func (m *Schema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schema.Marshal(b, m, deterministic)
}
func (m *Schema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schema.Merge(m, src)
}
func (m *Schema) XXX_Size() int {
	return xxx_messageInfo_Schema.Size(m)
}
func (m *Schema) XXX_DiscardUnknown() {
	xxx_messageInfo_Schema.DiscardUnknown(m)
}

var xxx_messageInfo_Schema proto.InternalMessageInfo

func (m *Schema) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Schema) GetAuthorized() bool {
	if m != nil {
		return m.Authorized
	}
	return false
}

func (m *Schema) GetDeprecated() bool {
	if m != nil {
		return m.Deprecated
	}
	return false
}

func (m *Schema) GetInput() []*Field {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *Schema) GetOutput() []*Field {
	if m != nil {
		return m.Output
	}
	return nil
}

//type NamespaceSchema struct {
//	Namespace   string `json:"namespace"`
//	Description string `json:"description"`
//	Operations  map[Operation]*Schema
//}
type NamespaceSchema struct {
	Namespace            string             `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Description          string             `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Operations           map[string]*Schema `protobuf:"bytes,3,rep,name=operations,proto3" json:"operations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *NamespaceSchema) Reset()         { *m = NamespaceSchema{} }
func (m *NamespaceSchema) String() string { return proto.CompactTextString(m) }
func (*NamespaceSchema) ProtoMessage()    {}
func (*NamespaceSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{3}
}

func (m *NamespaceSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamespaceSchema.Unmarshal(m, b)
}
func (m *NamespaceSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamespaceSchema.Marshal(b, m, deterministic)
}
func (m *NamespaceSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamespaceSchema.Merge(m, src)
}
func (m *NamespaceSchema) XXX_Size() int {
	return xxx_messageInfo_NamespaceSchema.Size(m)
}
func (m *NamespaceSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_NamespaceSchema.DiscardUnknown(m)
}

var xxx_messageInfo_NamespaceSchema proto.InternalMessageInfo

func (m *NamespaceSchema) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *NamespaceSchema) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *NamespaceSchema) GetOperations() map[string]*Schema {
	if m != nil {
		return m.Operations
	}
	return nil
}

type SchemaRequestReply struct {
	NamespaceSchemas     []*NamespaceSchema `protobuf:"bytes,1,rep,name=NamespaceSchemas,proto3" json:"NamespaceSchemas,omitempty"`
	Err                  string             `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SchemaRequestReply) Reset()         { *m = SchemaRequestReply{} }
func (m *SchemaRequestReply) String() string { return proto.CompactTextString(m) }
func (*SchemaRequestReply) ProtoMessage()    {}
func (*SchemaRequestReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{4}
}

func (m *SchemaRequestReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemaRequestReply.Unmarshal(m, b)
}
func (m *SchemaRequestReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemaRequestReply.Marshal(b, m, deterministic)
}
func (m *SchemaRequestReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemaRequestReply.Merge(m, src)
}
func (m *SchemaRequestReply) XXX_Size() int {
	return xxx_messageInfo_SchemaRequestReply.Size(m)
}
func (m *SchemaRequestReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemaRequestReply.DiscardUnknown(m)
}

var xxx_messageInfo_SchemaRequestReply proto.InternalMessageInfo

func (m *SchemaRequestReply) GetNamespaceSchemas() []*NamespaceSchema {
	if m != nil {
		return m.NamespaceSchemas
	}
	return nil
}

func (m *SchemaRequestReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*SchemaRequestArgs)(nil), "proto.SchemaRequestArgs")
	proto.RegisterType((*Field)(nil), "proto.Field")
	proto.RegisterType((*Schema)(nil), "proto.Schema")
	proto.RegisterType((*NamespaceSchema)(nil), "proto.NamespaceSchema")
	proto.RegisterMapType((map[string]*Schema)(nil), "proto.NamespaceSchema.OperationsEntry")
	proto.RegisterType((*SchemaRequestReply)(nil), "proto.SchemaRequestReply")
}

func init() {
	proto.RegisterFile("schema.proto", fileDescriptor_1c5fb4d8cc22d66a)
}

var fileDescriptor_1c5fb4d8cc22d66a = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4d, 0x6f, 0xd4, 0x30,
	0x14, 0x94, 0x37, 0x9b, 0x74, 0xf3, 0x52, 0xd4, 0x62, 0x50, 0x65, 0x55, 0x08, 0x45, 0x01, 0xa1,
	0x15, 0x87, 0x1c, 0xca, 0x05, 0xc1, 0x89, 0x4a, 0x54, 0x1c, 0x2a, 0x90, 0xcc, 0x8d, 0x9b, 0x49,
	0x5e, 0xa9, 0x69, 0x3e, 0x5c, 0xdb, 0x41, 0x2c, 0xbf, 0x8b, 0xff, 0xc3, 0x91, 0xbf, 0x81, 0xec,
	0xb8, 0xdd, 0x90, 0xdd, 0x93, 0xdf, 0xcc, 0xbc, 0xdd, 0x99, 0x89, 0x1e, 0x1c, 0x9a, 0xea, 0x1a,
	0x5b, 0x51, 0x2a, 0xdd, 0xdb, 0x9e, 0xc6, 0xfe, 0x29, 0x1e, 0xc1, 0xc3, 0xcf, 0x9e, 0xe6, 0x78,
	0x3b, 0xa0, 0xb1, 0xef, 0xf4, 0x37, 0x53, 0xfc, 0x21, 0x10, 0x5f, 0x48, 0x6c, 0x6a, 0xfa, 0x18,
	0xe2, 0x2b, 0x37, 0x30, 0x92, 0x93, 0x75, 0xca, 0x47, 0x40, 0x29, 0x2c, 0x3b, 0xd1, 0x22, 0x5b,
	0x78, 0xd2, 0xcf, 0x8e, 0xbb, 0x91, 0x5d, 0xcd, 0xa2, 0x91, 0x73, 0x33, 0x3d, 0x85, 0x95, 0xc6,
	0xdb, 0x41, 0x6a, 0xac, 0xd9, 0x32, 0x27, 0xeb, 0x15, 0xbf, 0xc7, 0xf4, 0x29, 0x40, 0x8d, 0x4a,
	0x63, 0x25, 0x2c, 0xd6, 0x2c, 0xf6, 0xea, 0x84, 0xa1, 0x27, 0x90, 0x48, 0x73, 0x29, 0x8d, 0x65,
	0x89, 0xd7, 0x02, 0xa2, 0x0c, 0x0e, 0xf0, 0xa7, 0x68, 0x55, 0x83, 0x6c, 0xe5, 0xad, 0xee, 0x20,
	0x7d, 0x09, 0xa9, 0xc6, 0x2b, 0xd4, 0xd8, 0x55, 0xc8, 0xd2, 0x3c, 0x5a, 0x67, 0x67, 0x87, 0x63,
	0xd9, 0xd2, 0x97, 0xe1, 0x5b, 0xb9, 0xf8, 0x4d, 0x20, 0x19, 0x7b, 0xd3, 0x1c, 0xb2, 0x1a, 0x4d,
	0xa5, 0xa5, 0xb2, 0xb2, 0xef, 0x42, 0xd1, 0x29, 0xe5, 0xa2, 0x8a, 0xc1, 0x5e, 0xf7, 0x5a, 0xfe,
	0xc2, 0xda, 0x97, 0x5e, 0xf1, 0x09, 0x33, 0xab, 0x12, 0xed, 0x54, 0x29, 0x20, 0x96, 0x9d, 0x1a,
	0x2c, 0x5b, 0xee, 0x09, 0x35, 0x4a, 0xf4, 0x39, 0x24, 0xfd, 0x60, 0xdd, 0x52, 0xbc, 0x67, 0x29,
	0x68, 0xc5, 0x5f, 0x02, 0x47, 0x1f, 0x45, 0x8b, 0x46, 0x89, 0x0a, 0x43, 0xfe, 0x27, 0x90, 0x76,
	0x77, 0x54, 0x48, 0xbf, 0x25, 0xe6, 0xed, 0x16, 0xbb, 0xed, 0x2e, 0x00, 0x7a, 0x85, 0x5a, 0x38,
	0x60, 0x58, 0xe4, 0xdd, 0x5f, 0x04, 0xf7, 0x99, 0x57, 0xf9, 0xe9, 0x7e, 0xf1, 0x7d, 0x67, 0xf5,
	0x86, 0x4f, 0x7e, 0x79, 0x7a, 0x09, 0x47, 0x33, 0x99, 0x1e, 0x43, 0x74, 0x83, 0x9b, 0x10, 0xca,
	0x8d, 0xf4, 0x19, 0xc4, 0x3f, 0x44, 0x33, 0x8c, 0xa7, 0x93, 0x9d, 0x3d, 0x08, 0x3e, 0xe1, 0x04,
	0x47, 0xed, 0xcd, 0xe2, 0x35, 0x29, 0xbe, 0x03, 0xfd, 0xef, 0x2e, 0x39, 0xaa, 0x66, 0x43, 0xcf,
	0xe1, 0x78, 0x16, 0xc9, 0x30, 0xe2, 0x13, 0x9f, 0xec, 0x4f, 0xcc, 0x77, 0xf6, 0x5d, 0x28, 0xd4,
	0x3a, 0x7c, 0x09, 0x37, 0x9e, 0x67, 0x1f, 0x16, 0x5f, 0x0e, 0xca, 0xb7, 0xfe, 0x0f, 0xbe, 0x26,
	0xfe, 0x79, 0xf5, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x3a, 0xeb, 0xb4, 0xe0, 0x2e, 0x03, 0x00, 0x00,
}
