// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StorageEntry struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageEntry) Reset()         { *m = StorageEntry{} }
func (m *StorageEntry) String() string { return proto.CompactTextString(m) }
func (*StorageEntry) ProtoMessage()    {}
func (*StorageEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{0}
}

func (m *StorageEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageEntry.Unmarshal(m, b)
}
func (m *StorageEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageEntry.Marshal(b, m, deterministic)
}
func (m *StorageEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageEntry.Merge(m, src)
}
func (m *StorageEntry) XXX_Size() int {
	return xxx_messageInfo_StorageEntry.Size(m)
}
func (m *StorageEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageEntry.DiscardUnknown(m)
}

var xxx_messageInfo_StorageEntry proto.InternalMessageInfo

func (m *StorageEntry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *StorageEntry) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type StorageListArgs struct {
	Prefix               string   `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageListArgs) Reset()         { *m = StorageListArgs{} }
func (m *StorageListArgs) String() string { return proto.CompactTextString(m) }
func (*StorageListArgs) ProtoMessage()    {}
func (*StorageListArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{1}
}

func (m *StorageListArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageListArgs.Unmarshal(m, b)
}
func (m *StorageListArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageListArgs.Marshal(b, m, deterministic)
}
func (m *StorageListArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageListArgs.Merge(m, src)
}
func (m *StorageListArgs) XXX_Size() int {
	return xxx_messageInfo_StorageListArgs.Size(m)
}
func (m *StorageListArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageListArgs.DiscardUnknown(m)
}

var xxx_messageInfo_StorageListArgs proto.InternalMessageInfo

func (m *StorageListArgs) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

type StorageListReply struct {
	Entities             []*StorageEntry `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	Err                  string          `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StorageListReply) Reset()         { *m = StorageListReply{} }
func (m *StorageListReply) String() string { return proto.CompactTextString(m) }
func (*StorageListReply) ProtoMessage()    {}
func (*StorageListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{2}
}

func (m *StorageListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageListReply.Unmarshal(m, b)
}
func (m *StorageListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageListReply.Marshal(b, m, deterministic)
}
func (m *StorageListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageListReply.Merge(m, src)
}
func (m *StorageListReply) XXX_Size() int {
	return xxx_messageInfo_StorageListReply.Size(m)
}
func (m *StorageListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageListReply.DiscardUnknown(m)
}

var xxx_messageInfo_StorageListReply proto.InternalMessageInfo

func (m *StorageListReply) GetEntities() []*StorageEntry {
	if m != nil {
		return m.Entities
	}
	return nil
}

func (m *StorageListReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type StorageGetArgs struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageGetArgs) Reset()         { *m = StorageGetArgs{} }
func (m *StorageGetArgs) String() string { return proto.CompactTextString(m) }
func (*StorageGetArgs) ProtoMessage()    {}
func (*StorageGetArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{3}
}

func (m *StorageGetArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageGetArgs.Unmarshal(m, b)
}
func (m *StorageGetArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageGetArgs.Marshal(b, m, deterministic)
}
func (m *StorageGetArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageGetArgs.Merge(m, src)
}
func (m *StorageGetArgs) XXX_Size() int {
	return xxx_messageInfo_StorageGetArgs.Size(m)
}
func (m *StorageGetArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageGetArgs.DiscardUnknown(m)
}

var xxx_messageInfo_StorageGetArgs proto.InternalMessageInfo

func (m *StorageGetArgs) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type StorageGetReply struct {
	Entry                *StorageEntry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	Err                  string        `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StorageGetReply) Reset()         { *m = StorageGetReply{} }
func (m *StorageGetReply) String() string { return proto.CompactTextString(m) }
func (*StorageGetReply) ProtoMessage()    {}
func (*StorageGetReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{4}
}

func (m *StorageGetReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageGetReply.Unmarshal(m, b)
}
func (m *StorageGetReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageGetReply.Marshal(b, m, deterministic)
}
func (m *StorageGetReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageGetReply.Merge(m, src)
}
func (m *StorageGetReply) XXX_Size() int {
	return xxx_messageInfo_StorageGetReply.Size(m)
}
func (m *StorageGetReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageGetReply.DiscardUnknown(m)
}

var xxx_messageInfo_StorageGetReply proto.InternalMessageInfo

func (m *StorageGetReply) GetEntry() *StorageEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func (m *StorageGetReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type StoragePutArgs struct {
	Entry                *StorageEntry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StoragePutArgs) Reset()         { *m = StoragePutArgs{} }
func (m *StoragePutArgs) String() string { return proto.CompactTextString(m) }
func (*StoragePutArgs) ProtoMessage()    {}
func (*StoragePutArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{5}
}

func (m *StoragePutArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoragePutArgs.Unmarshal(m, b)
}
func (m *StoragePutArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoragePutArgs.Marshal(b, m, deterministic)
}
func (m *StoragePutArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoragePutArgs.Merge(m, src)
}
func (m *StoragePutArgs) XXX_Size() int {
	return xxx_messageInfo_StoragePutArgs.Size(m)
}
func (m *StoragePutArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_StoragePutArgs.DiscardUnknown(m)
}

var xxx_messageInfo_StoragePutArgs proto.InternalMessageInfo

func (m *StoragePutArgs) GetEntry() *StorageEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type StoragePutReply struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoragePutReply) Reset()         { *m = StoragePutReply{} }
func (m *StoragePutReply) String() string { return proto.CompactTextString(m) }
func (*StoragePutReply) ProtoMessage()    {}
func (*StoragePutReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{6}
}

func (m *StoragePutReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoragePutReply.Unmarshal(m, b)
}
func (m *StoragePutReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoragePutReply.Marshal(b, m, deterministic)
}
func (m *StoragePutReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoragePutReply.Merge(m, src)
}
func (m *StoragePutReply) XXX_Size() int {
	return xxx_messageInfo_StoragePutReply.Size(m)
}
func (m *StoragePutReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StoragePutReply.DiscardUnknown(m)
}

var xxx_messageInfo_StoragePutReply proto.InternalMessageInfo

func (m *StoragePutReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type StorageDeleteArgs struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageDeleteArgs) Reset()         { *m = StorageDeleteArgs{} }
func (m *StorageDeleteArgs) String() string { return proto.CompactTextString(m) }
func (*StorageDeleteArgs) ProtoMessage()    {}
func (*StorageDeleteArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{7}
}

func (m *StorageDeleteArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageDeleteArgs.Unmarshal(m, b)
}
func (m *StorageDeleteArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageDeleteArgs.Marshal(b, m, deterministic)
}
func (m *StorageDeleteArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageDeleteArgs.Merge(m, src)
}
func (m *StorageDeleteArgs) XXX_Size() int {
	return xxx_messageInfo_StorageDeleteArgs.Size(m)
}
func (m *StorageDeleteArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageDeleteArgs.DiscardUnknown(m)
}

var xxx_messageInfo_StorageDeleteArgs proto.InternalMessageInfo

func (m *StorageDeleteArgs) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type StorageDeleteReply struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageDeleteReply) Reset()         { *m = StorageDeleteReply{} }
func (m *StorageDeleteReply) String() string { return proto.CompactTextString(m) }
func (*StorageDeleteReply) ProtoMessage()    {}
func (*StorageDeleteReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{8}
}

func (m *StorageDeleteReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageDeleteReply.Unmarshal(m, b)
}
func (m *StorageDeleteReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageDeleteReply.Marshal(b, m, deterministic)
}
func (m *StorageDeleteReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageDeleteReply.Merge(m, src)
}
func (m *StorageDeleteReply) XXX_Size() int {
	return xxx_messageInfo_StorageDeleteReply.Size(m)
}
func (m *StorageDeleteReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageDeleteReply.DiscardUnknown(m)
}

var xxx_messageInfo_StorageDeleteReply proto.InternalMessageInfo

func (m *StorageDeleteReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*StorageEntry)(nil), "proto.StorageEntry")
	proto.RegisterType((*StorageListArgs)(nil), "proto.StorageListArgs")
	proto.RegisterType((*StorageListReply)(nil), "proto.StorageListReply")
	proto.RegisterType((*StorageGetArgs)(nil), "proto.StorageGetArgs")
	proto.RegisterType((*StorageGetReply)(nil), "proto.StorageGetReply")
	proto.RegisterType((*StoragePutArgs)(nil), "proto.StoragePutArgs")
	proto.RegisterType((*StoragePutReply)(nil), "proto.StoragePutReply")
	proto.RegisterType((*StorageDeleteArgs)(nil), "proto.StorageDeleteArgs")
	proto.RegisterType((*StorageDeleteReply)(nil), "proto.StorageDeleteReply")
}

func init() {
	proto.RegisterFile("storage.proto", fileDescriptor_0d2c4ccf1453ffdb)
}

var fileDescriptor_0d2c4ccf1453ffdb = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xd9, 0xd6, 0xb6, 0x76, 0x5a, 0xb5, 0xae, 0x5a, 0x63, 0x4f, 0x61, 0x45, 0x49, 0x2f,
	0x11, 0xaa, 0xe8, 0xa1, 0x78, 0x50, 0x94, 0x78, 0x10, 0x09, 0x11, 0x2f, 0xde, 0x2a, 0x8c, 0x25,
	0x18, 0x9a, 0xb0, 0xd9, 0x88, 0xf9, 0xd0, 0x7e, 0x07, 0xc9, 0xee, 0xba, 0x6d, 0x4c, 0x03, 0x9e,
	0xf6, 0xcf, 0xbc, 0x37, 0xef, 0xb7, 0xb3, 0xb0, 0x95, 0x8a, 0x98, 0xcf, 0xe6, 0xe8, 0x26, 0x3c,
	0x16, 0x31, 0x6d, 0xc9, 0x85, 0x5d, 0x42, 0xff, 0x59, 0xdd, 0xdf, 0x2f, 0x04, 0xcf, 0xe9, 0x00,
	0x9a, 0x1f, 0x98, 0x5b, 0xc4, 0x26, 0x4e, 0x37, 0x28, 0xb6, 0x74, 0x1f, 0x5a, 0x9f, 0xb3, 0x28,
	0x43, 0xab, 0x61, 0x13, 0xa7, 0x1f, 0xa8, 0x03, 0x1b, 0xc3, 0x8e, 0xf6, 0x3d, 0x86, 0xa9, 0xb8,
	0xe1, 0xf3, 0x94, 0x0e, 0xa1, 0x9d, 0x70, 0x7c, 0x0f, 0xbf, 0xb4, 0x5b, 0x9f, 0xd8, 0x0b, 0x0c,
	0x56, 0xa4, 0x01, 0x26, 0x51, 0x4e, 0xcf, 0x60, 0x13, 0x17, 0x22, 0x14, 0x21, 0xa6, 0x16, 0xb1,
	0x9b, 0x4e, 0x6f, 0xb2, 0xa7, 0xb8, 0xdc, 0x55, 0x9a, 0xc0, 0x88, 0x0a, 0x2e, 0xe4, 0x5c, 0x32,
	0x74, 0x83, 0x62, 0xcb, 0x18, 0x6c, 0x6b, 0xad, 0x87, 0x0a, 0xa0, 0xc2, 0xce, 0x9e, 0x0c, 0xa5,
	0x87, 0x3a, 0x79, 0x0c, 0x2d, 0x2c, 0x7a, 0x4b, 0x59, 0x4d, 0xac, 0x52, 0xac, 0xc9, 0x9c, 0x9a,
	0x4c, 0x3f, 0x53, 0x99, 0xff, 0x6f, 0xc7, 0x8e, 0x0d, 0x8c, 0x9f, 0x69, 0x18, 0x9d, 0x40, 0x96,
	0x09, 0x27, 0xb0, 0xab, 0x45, 0x77, 0x18, 0xa1, 0xc0, 0x9a, 0x87, 0x9d, 0x02, 0x2d, 0xc9, 0x6a,
	0xda, 0x4d, 0xbe, 0x09, 0x74, 0xb4, 0x90, 0x5e, 0xc1, 0x46, 0xf1, 0x01, 0x74, 0x58, 0x66, 0xfc,
	0xfd, 0xbf, 0xd1, 0x61, 0xf5, 0x5e, 0xb5, 0xbd, 0x80, 0xa6, 0x87, 0x82, 0x1e, 0x94, 0xeb, 0x7a,
	0xea, 0xa3, 0x61, 0xe5, 0xda, 0xb8, 0xfc, 0xac, 0xe2, 0xd2, 0x73, 0xfb, 0xeb, 0x32, 0x13, 0xb9,
	0x86, 0xb6, 0x7a, 0x11, 0xb5, 0xca, 0x8a, 0xe5, 0x38, 0x46, 0x47, 0xeb, 0x2a, 0xd2, 0x7e, 0xdb,
	0x7b, 0x68, 0xbc, 0x76, 0xdc, 0xa9, 0xac, 0xbf, 0xb5, 0xe5, 0x72, 0xfe, 0x13, 0x00, 0x00, 0xff,
	0xff, 0x14, 0x56, 0x89, 0x18, 0xfa, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StorageClient is the client API for Storage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageClient interface {
	List(ctx context.Context, in *StorageListArgs, opts ...grpc.CallOption) (*StorageListReply, error)
	Get(ctx context.Context, in *StorageGetArgs, opts ...grpc.CallOption) (*StorageGetReply, error)
	Put(ctx context.Context, in *StoragePutArgs, opts ...grpc.CallOption) (*StoragePutReply, error)
	Delete(ctx context.Context, in *StorageDeleteArgs, opts ...grpc.CallOption) (*StorageDeleteReply, error)
}

type storageClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageClient(cc grpc.ClientConnInterface) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) List(ctx context.Context, in *StorageListArgs, opts ...grpc.CallOption) (*StorageListReply, error) {
	out := new(StorageListReply)
	err := c.cc.Invoke(ctx, "/proto.Storage/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) Get(ctx context.Context, in *StorageGetArgs, opts ...grpc.CallOption) (*StorageGetReply, error) {
	out := new(StorageGetReply)
	err := c.cc.Invoke(ctx, "/proto.Storage/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) Put(ctx context.Context, in *StoragePutArgs, opts ...grpc.CallOption) (*StoragePutReply, error) {
	out := new(StoragePutReply)
	err := c.cc.Invoke(ctx, "/proto.Storage/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) Delete(ctx context.Context, in *StorageDeleteArgs, opts ...grpc.CallOption) (*StorageDeleteReply, error) {
	out := new(StorageDeleteReply)
	err := c.cc.Invoke(ctx, "/proto.Storage/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServer is the server API for Storage service.
type StorageServer interface {
	List(context.Context, *StorageListArgs) (*StorageListReply, error)
	Get(context.Context, *StorageGetArgs) (*StorageGetReply, error)
	Put(context.Context, *StoragePutArgs) (*StoragePutReply, error)
	Delete(context.Context, *StorageDeleteArgs) (*StorageDeleteReply, error)
}

// UnimplementedStorageServer can be embedded to have forward compatible implementations.
type UnimplementedStorageServer struct {
}

func (*UnimplementedStorageServer) List(ctx context.Context, req *StorageListArgs) (*StorageListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedStorageServer) Get(ctx context.Context, req *StorageGetArgs) (*StorageGetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedStorageServer) Put(ctx context.Context, req *StoragePutArgs) (*StoragePutReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (*UnimplementedStorageServer) Delete(ctx context.Context, req *StorageDeleteArgs) (*StorageDeleteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterStorageServer(s *grpc.Server, srv StorageServer) {
	s.RegisterService(&_Storage_serviceDesc, srv)
}

func _Storage_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageListArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Storage/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).List(ctx, req.(*StorageListArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageGetArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Storage/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).Get(ctx, req.(*StorageGetArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoragePutArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Storage/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).Put(ctx, req.(*StoragePutArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageDeleteArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Storage/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).Delete(ctx, req.(*StorageDeleteArgs))
	}
	return interceptor(ctx, in, info, handler)
}

var _Storage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Storage",
	HandlerType: (*StorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Storage_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Storage_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _Storage_Put_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Storage_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}
